@startuml

!include skin.puml
skinparam shadowing true

(*) --> "Create Job"
--> "Create Tasks"
--> "Submit Job"
--> ===T1===
===T1=== --> "Run Task 1"
===T1=== --> "Run Task 2"
===T1=== --> "Run Task n"
"Run Task 1" --> "Run Map 1"
"Run Task 2" --> "Run Map 2"
"Run Task n" --> "Run Map n"
"Run Map 1" --> "Partitions 1..m" as P1
"Run Map 2" --> "Partitions 1..m" as P2
"Run Map n" --> "Partitions 1..m" as PN
P1 --> ===M1===
P2 --> ===M1===
PN --> ===M1===
===M1=== --> "Shuffle"
--> ===R1===
===R1=== --> "Run Reduce 1"
===R1=== --> "Run Reduce 2"
===R1=== --> "Run Reduce m"
"Run Reduce 1" --> ===R2===
"Run Reduce 2" --> ===R2===
"Run Reduce m" --> ===R2===
===R2=== --> (*)
@enduml