@startuml

!include skin.puml

activate JavaBaseLibraryFunction
JavaBaseLibraryFunction -> JavaBaseLibraryFunction : setInParameters(inParams : String[])
JavaBaseLibraryFunction -> MapJavaBaseLibraryFunction : run(parameters : List<String>)

activate MapJavaBaseLibraryFunction
MapJavaBaseLibraryFunction -> WordCountMap : runMap(parameters : List<String>)

activate WordCountMap
loop for every word in parameters
WordCountMap -> MapJavaBaseLibraryFunction : emit(word : String, 1 : int)
activate MapJavaBaseLibraryFunction
WordCountMap <-- MapJavaBaseLibraryFunction
deactivate MapJavaBaseLibraryFunction
end
MapJavaBaseLibraryFunction <-- WordCountMap
deactivate WordCountMap

MapJavaBaseLibraryFunction -> JavaBaseLibraryFunction : setResult(mapResult : JsonArray)
activate JavaBaseLibraryFunction
MapJavaBaseLibraryFunction <-- JavaBaseLibraryFunction
deactivate JavaBaseLibraryFunction
JavaBaseLibraryFunction <-- MapJavaBaseLibraryFunction
deactivate MapJavaBaseLibraryFunction

deactivate JavaBaseLibraryFunction
@enduml